### ISSUE TITLE
Large map under "accommodation" is blank

### ISSUE THREAD

**Issue by gvwilson** [carpentrycon/carpentrycon2018#8]
The large map of Dublin under the heading "University College Dublin" is blank.

**Comment by weaverbel** [comment]
Hi @gvwilson Not broken for me ! Can you try again? Maybe it was a glitch.

**Comment by katrinleinweber** [comment]
Seems to depend on JavaScript being allowed for `openstreetmap.org` and/or `www.openstreetmap.org`.
